networks:
  media_cloud_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.250.0/24

services:
  api:
    image: media_cloud_backend:0.4
    container_name: media-cloud-api
    env_file:
      - ${APP_ENV_FILE:-.env}
    environment:
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS:-*}
      APP_WORKERS: ${APP_WORKERS:-2}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-60}
      GUNICORN_KEEPALIVE: ${GUNICORN_KEEPALIVE:-5}
    ports:
      - "127.0.0.1:${APP_PORT:-8000}:${APP_PORT:-8000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    networks:
      - media_cloud_net
